version: '3.8'
services:
    postgres:
        image: postgres
        container_name: postgres
        hostname: postgresql
        volumes:
          - postgresdata:/var/lib/postgresql/data
        ports:
          - "5432:5432"
        env_file:
          - .env

volumes:
    postgresdata:

