version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgresql
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
  apiserver:
    build: ./server
    image: apiserver
    container_name: apiserver
    volumes:
      - ./server:/server
      - ./.env:/.env:ro
    ports:
      - "8000:8000"
    command: uvicorn server.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - "postgres"

volumes:
  postgresdata:


